/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedNewOrgRouteImport } from './routes/_authed/new-org'
import { Route as AuthedProjectsProjectIdRouteImport } from './routes/_authed/projects/$projectId'
import { Route as AuthedOrgOrgIdRouteImport } from './routes/_authed/org/$orgId'
import { Route as AuthedProjectsProjectIdIndexRouteImport } from './routes/_authed/projects/$projectId/index'
import { Route as AuthedOrgOrgIdIndexRouteImport } from './routes/_authed/org/$orgId/index'
import { Route as AuthedProjectsProjectIdTracesRouteImport } from './routes/_authed/projects/$projectId/traces'
import { Route as AuthedProjectsProjectIdSettingsRouteImport } from './routes/_authed/projects/$projectId/settings'
import { Route as AuthedOrgOrgIdSettingsRouteImport } from './routes/_authed/org/$orgId/settings'
import { Route as AuthedOrgOrgIdNewRouteImport } from './routes/_authed/org/$orgId/new'
import { Route as AuthedProjectsProjectIdTraceTraceIdRouteImport } from './routes/_authed/projects/$projectId/trace.$traceId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewOrgRoute = AuthedNewOrgRouteImport.update({
  id: '/new-org',
  path: '/new-org',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdRoute = AuthedProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrgIdRoute = AuthedOrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdIndexRoute =
  AuthedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedOrgOrgIdIndexRoute = AuthedOrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgOrgIdRoute,
} as any)
const AuthedProjectsProjectIdTracesRoute =
  AuthedProjectsProjectIdTracesRouteImport.update({
    id: '/traces',
    path: '/traces',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdSettingsRoute =
  AuthedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedOrgOrgIdSettingsRoute = AuthedOrgOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedOrgOrgIdRoute,
} as any)
const AuthedOrgOrgIdNewRoute = AuthedOrgOrgIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedOrgOrgIdRoute,
} as any)
const AuthedProjectsProjectIdTraceTraceIdRoute =
  AuthedProjectsProjectIdTraceTraceIdRouteImport.update({
    id: '/trace/$traceId',
    path: '/trace/$traceId',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/new-org': typeof AuthedNewOrgRoute
  '/settings': typeof AuthedSettingsRoute
  '/org/$orgId': typeof AuthedOrgOrgIdRouteWithChildren
  '/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/org/$orgId/new': typeof AuthedOrgOrgIdNewRoute
  '/org/$orgId/settings': typeof AuthedOrgOrgIdSettingsRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/projects/$projectId/traces': typeof AuthedProjectsProjectIdTracesRoute
  '/org/$orgId/': typeof AuthedOrgOrgIdIndexRoute
  '/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/projects/$projectId/trace/$traceId': typeof AuthedProjectsProjectIdTraceTraceIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/new-org': typeof AuthedNewOrgRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/org/$orgId/new': typeof AuthedOrgOrgIdNewRoute
  '/org/$orgId/settings': typeof AuthedOrgOrgIdSettingsRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/projects/$projectId/traces': typeof AuthedProjectsProjectIdTracesRoute
  '/org/$orgId': typeof AuthedOrgOrgIdIndexRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdIndexRoute
  '/projects/$projectId/trace/$traceId': typeof AuthedProjectsProjectIdTraceTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/new-org': typeof AuthedNewOrgRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/org/$orgId': typeof AuthedOrgOrgIdRouteWithChildren
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/_authed/org/$orgId/new': typeof AuthedOrgOrgIdNewRoute
  '/_authed/org/$orgId/settings': typeof AuthedOrgOrgIdSettingsRoute
  '/_authed/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/_authed/projects/$projectId/traces': typeof AuthedProjectsProjectIdTracesRoute
  '/_authed/org/$orgId/': typeof AuthedOrgOrgIdIndexRoute
  '/_authed/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/_authed/projects/$projectId/trace/$traceId': typeof AuthedProjectsProjectIdTraceTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/new-org'
    | '/settings'
    | '/org/$orgId'
    | '/projects/$projectId'
    | '/org/$orgId/new'
    | '/org/$orgId/settings'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/traces'
    | '/org/$orgId/'
    | '/projects/$projectId/'
    | '/projects/$projectId/trace/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/new-org'
    | '/settings'
    | '/'
    | '/org/$orgId/new'
    | '/org/$orgId/settings'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/traces'
    | '/org/$orgId'
    | '/projects/$projectId'
    | '/projects/$projectId/trace/$traceId'
  id:
    | '__root__'
    | '/_authed'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/_authed/new-org'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/org/$orgId'
    | '/_authed/projects/$projectId'
    | '/_authed/org/$orgId/new'
    | '/_authed/org/$orgId/settings'
    | '/_authed/projects/$projectId/settings'
    | '/_authed/projects/$projectId/traces'
    | '/_authed/org/$orgId/'
    | '/_authed/projects/$projectId/'
    | '/_authed/projects/$projectId/trace/$traceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/new-org': {
      id: '/_authed/new-org'
      path: '/new-org'
      fullPath: '/new-org'
      preLoaderRoute: typeof AuthedNewOrgRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$orgId': {
      id: '/_authed/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof AuthedOrgOrgIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/org/$orgId/': {
      id: '/_authed/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof AuthedOrgOrgIdIndexRouteImport
      parentRoute: typeof AuthedOrgOrgIdRoute
    }
    '/_authed/projects/$projectId/traces': {
      id: '/_authed/projects/$projectId/traces'
      path: '/traces'
      fullPath: '/projects/$projectId/traces'
      preLoaderRoute: typeof AuthedProjectsProjectIdTracesRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/settings': {
      id: '/_authed/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/org/$orgId/settings': {
      id: '/_authed/org/$orgId/settings'
      path: '/settings'
      fullPath: '/org/$orgId/settings'
      preLoaderRoute: typeof AuthedOrgOrgIdSettingsRouteImport
      parentRoute: typeof AuthedOrgOrgIdRoute
    }
    '/_authed/org/$orgId/new': {
      id: '/_authed/org/$orgId/new'
      path: '/new'
      fullPath: '/org/$orgId/new'
      preLoaderRoute: typeof AuthedOrgOrgIdNewRouteImport
      parentRoute: typeof AuthedOrgOrgIdRoute
    }
    '/_authed/projects/$projectId/trace/$traceId': {
      id: '/_authed/projects/$projectId/trace/$traceId'
      path: '/trace/$traceId'
      fullPath: '/projects/$projectId/trace/$traceId'
      preLoaderRoute: typeof AuthedProjectsProjectIdTraceTraceIdRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
  }
}

interface AuthedOrgOrgIdRouteChildren {
  AuthedOrgOrgIdNewRoute: typeof AuthedOrgOrgIdNewRoute
  AuthedOrgOrgIdSettingsRoute: typeof AuthedOrgOrgIdSettingsRoute
  AuthedOrgOrgIdIndexRoute: typeof AuthedOrgOrgIdIndexRoute
}

const AuthedOrgOrgIdRouteChildren: AuthedOrgOrgIdRouteChildren = {
  AuthedOrgOrgIdNewRoute: AuthedOrgOrgIdNewRoute,
  AuthedOrgOrgIdSettingsRoute: AuthedOrgOrgIdSettingsRoute,
  AuthedOrgOrgIdIndexRoute: AuthedOrgOrgIdIndexRoute,
}

const AuthedOrgOrgIdRouteWithChildren = AuthedOrgOrgIdRoute._addFileChildren(
  AuthedOrgOrgIdRouteChildren,
)

interface AuthedProjectsProjectIdRouteChildren {
  AuthedProjectsProjectIdSettingsRoute: typeof AuthedProjectsProjectIdSettingsRoute
  AuthedProjectsProjectIdTracesRoute: typeof AuthedProjectsProjectIdTracesRoute
  AuthedProjectsProjectIdIndexRoute: typeof AuthedProjectsProjectIdIndexRoute
  AuthedProjectsProjectIdTraceTraceIdRoute: typeof AuthedProjectsProjectIdTraceTraceIdRoute
}

const AuthedProjectsProjectIdRouteChildren: AuthedProjectsProjectIdRouteChildren =
  {
    AuthedProjectsProjectIdSettingsRoute: AuthedProjectsProjectIdSettingsRoute,
    AuthedProjectsProjectIdTracesRoute: AuthedProjectsProjectIdTracesRoute,
    AuthedProjectsProjectIdIndexRoute: AuthedProjectsProjectIdIndexRoute,
    AuthedProjectsProjectIdTraceTraceIdRoute:
      AuthedProjectsProjectIdTraceTraceIdRoute,
  }

const AuthedProjectsProjectIdRouteWithChildren =
  AuthedProjectsProjectIdRoute._addFileChildren(
    AuthedProjectsProjectIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedNewOrgRoute: typeof AuthedNewOrgRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrgOrgIdRoute: typeof AuthedOrgOrgIdRouteWithChildren
  AuthedProjectsProjectIdRoute: typeof AuthedProjectsProjectIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedNewOrgRoute: AuthedNewOrgRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrgOrgIdRoute: AuthedOrgOrgIdRouteWithChildren,
  AuthedProjectsProjectIdRoute: AuthedProjectsProjectIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
